### ISSUE TITLE
Blocker list for V3

### ISSUE THREAD

**Issue by deajan** [netinvent/npbackup#59]
This is the current list of things to sort out before releasing next beta.

- [X] GUI: Move global prometheus config from repo config to global config
  - Done in https://github.com/netinvent/npbackup/commit/56686ec24121c241b744908b92ec0aee9957d57b
- [x] Test multiple pre/post exec script execution #13 
- [X] Make ${BACKUP_JOB} expansion work with repo_config ${BACKUP_JOB} value
- [x] Compile and test `-c` parameter
- [X] Compile and test --stdin on windows and linux #45
- [x] Test retention policy #27
   - [x] Make policy work in group operation CLI mode
- [x] Test S3 backend
- [X] Test remote backend failure #39
- [x] Changing repo_uri in config is not updated immediatly in main gui
- [x] Make sure metrics get uploaded in GUI
- [x] Optimize speed for ls operation
- [x] Fix inheritance (repo = false, group = true should give false)
- [x] Save GUI manager password
- [x] Check prometheus global propagation in config file
- [x] Windows / Linux task creation GUI / CLI command

The followling list must be sorted in RC

- [x] Added `-no-cache` option for RO systems
- [x]  Compiled GUI fails on KDE 6 /Xwayland, see #62 
- [x] Show permissions in --show-config and GUI
- [x] Show audience in config file
- [x] Fix `--snapshots` command when False is returned (check in RO system) 
- [X] Try to load exclusion files relative from current executable if not found
- [X] Multi-repo creation doesn't work
- [x]  Housekeeping doesn't work properly
- [x] Need more feedback

The following list must be sorted out before going final

- [x] Recheck all functions for CLI, GUI and viewer
- [x] Update grafana dashboard to include new metrics
- [x] Make customization easier for images and icons
- [x] Improve documentation
- [x] Create new default configuration files for linux and windows
- [x] Make new installer (get rid of Python installer which basically just added task creation. SFX ? Nullsoft ? What about AV engines ?) #35 

Any help, especially testing, and writing unit tests, is highly welcome.

**Comment by deajan** [comment]
Finally some good news, we're really close to a v3.0.0 release.
Program is running for months, and the feedback gained helped improve major parts of the monitoring as well as general UX.

**Comment by lcswillems** [comment]
Hello @deajan! It looks very interesting! By any chance, do you have any ETA? If not, no worries at all.

**Comment by deajan** [comment]
@lcswillems rc12 and rc13 run on all my setups, on windows, linux and nas devices.
Currently testing bigger upgrade scenarios. Once this is done, RTM is released.
I hope to have a release ready this week.

**Comment by lcswillems** [comment]
Awesome! Thanks for the info! :pray:

**Comment by lcswillems** [comment]
@deajan No worries at all! Good luck for what remains!

**Comment by deajan** [comment]
@lcswillems Well, there will be another RC.
I've rewritten some of the upgrade server / client stuff for bigger customer setups to work well.
So far so good, I pull an upgrade script from server, which doesn't make some AV engines happy (imagine a program that downloads and executes a script, that's some heuristic trigger).
So I am using an inline script, but batch is a hell of a language (had to make a [very big one liner with conditions](https://github.com/netinvent/npbackup/commit/9bc932cd141837b38adaf599ae98723aac2e8181))

So I hoped for a release two weeks ago, but I definitly need another round of upgrade tests, since it will be deployed on alot of machines, no one wants to realise that the remote upgrade feature is buggy ^^

**Comment by lcswillems** [comment]
Fully approve this way of thinking!!

**Comment by deajan** [comment]
Released RC14 today with all the improvements / fixes for upgrade server necessary for enterprise deployments.
Finally it took time. I really hope to have an official release shortly.

**Comment by deajan** [comment]
Finally, RTM has been released today.
@lcswillems Sorry for the delay ;)
